stages:
 - build
 - dockerize
 - deploy

services:
 - docker:dind

build backend:
 image: maven:alpine
 stage: build
 tags:
  - docker
 script:
  - mvn -s settings.xml install
 artifacts:
  paths:
   - ./target
   - ./.m2
  expire_in: 1 day

build frontend:
 image: node
 stage: build
 tags:
  - docker
 script:
  - pushd scipio-frontend
  - npm install
  - npm install -g @angular/cli
  - ng build --prod --output-path ../src/main/resources/static
  - popd
 artifacts:
  paths:
   - ./src/main/resources/static
  expire_in: 1 day

dockerize with version:
 image: docker
 stage: dockerize
 tags:
  - docker
 only:
  - tags
 script:
  - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
  - docker build . -t kykysenpai/scipio:$CI_COMMIT_TAG
  - docker push kykysenpai/scipio:$CI_COMMIT_TAG

dockerize as latest:
 image: docker
 stage: dockerize
 tags:
  - docker
 script:
  - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
  - docker build . -t kykysenpai/scipio
  - docker push kykysenpai/scipio

deploy in development environment:
 image: ubuntu
 stage: deploy
 tags:
  - docker
 before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
 script:
  - ssh -t kyky@server.mytcc.be "~/deploy_dev_scipio.sh"
 environment:
  name: development
  url: https://dev.scipio.mytcc.be
 when: manual

deploy in production environment:
 image: ubuntu
 stage: deploy
 tags:
  - docker
 before_script: 
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
 script:
  - ssh -t kyky@server.mytcc.be "~/deploy_prod_scipio.sh $CI_COMMIT_TAG"
 environment:
  name: production
  url: https://scipio.mytcc.be
 when: manual
 only:
  - tags
